/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package multiclient;

import javax.swing.JFileChooser;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import static multiclient.Test3.resizeImageIcon;

/**
 *
 * @author Sadia
 */
public class ClientFrame extends javax.swing.JFrame {
    public boolean clientTerminate;
    public String pathName;

    /**
     * Creates new form ClientFrame
     */
    public ClientFrame() {
        initComponents();
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        iptext = new javax.swing.JTextField();
        ipLabel = new javax.swing.JLabel();
        startClient = new javax.swing.JButton();
        requestLabel = new javax.swing.JLabel();
        endScreenShare = new javax.swing.JButton();
        imgLabel = new javax.swing.JLabel();
        getGif = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(400, 400));
        setPreferredSize(new java.awt.Dimension(400, 420));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(215, 240, 240));
        jPanel1.setForeground(new java.awt.Color(0, 125, 25));
        jPanel1.setLayout(null);
        jPanel1.add(iptext);
        iptext.setBounds(276, 141, 190, 30);

        ipLabel.setFont(new java.awt.Font("Gulim", 1, 12)); // NOI18N
        ipLabel.setText("Ip address :");
        jPanel1.add(ipLabel);
        ipLabel.setBounds(160, 140, 100, 30);

        startClient.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        startClient.setText("START");
        startClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startClientActionPerformed(evt);
            }
        });
        jPanel1.add(startClient);
        startClient.setBounds(280, 210, 190, 50);

        requestLabel.setFont(new java.awt.Font("Old English Text MT", 1, 18)); // NOI18N
        requestLabel.setForeground(new java.awt.Color(255, 255, 255));
        requestLabel.setText("Client is requesting.....");
        jPanel1.add(requestLabel);
        requestLabel.setBounds(219, 66, 240, 40);

        endScreenShare.setFont(new java.awt.Font("Cooper Black", 1, 18)); // NOI18N
        endScreenShare.setText("STOP !!");
        endScreenShare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                endScreenShareActionPerformed(evt);
            }
        });
        jPanel1.add(endScreenShare);
        endScreenShare.setBounds(0, 0, 120, 80);
        jPanel1.add(imgLabel);
        imgLabel.setBounds(0, 0, 0, 0);

        getGif.setFont(new java.awt.Font("Perpetua Titling MT", 1, 12)); // NOI18N
        getGif.setText("Choose Directory");
        getGif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getGifActionPerformed(evt);
            }
        });
        jPanel1.add(getGif);
        getGif.setBounds(280, 300, 190, 50);

        jLabel1.setIcon(new ImageIcon("home.jpg"));
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 930, 550);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1400, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
     
    public void init() {
        setSize(new java.awt.Dimension(600, 600));
        ipLabel.setVisible(true);
        requestLabel.setVisible(false);
        iptext.setVisible(true);
        startClient.setVisible(true);
        endScreenShare.setVisible(false);
        imgLabel.setVisible(false);
        clientTerminate= false;
        
    }
    private void startClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startClientActionPerformed
        // TODO add your handling code here:
        
        if (iptext.getText().trim().length() < 0) {
            JOptionPane.showMessageDialog(this, "Please Enter Ip address");
            return;
        }
        
        getGif.setVisible(false); 
        ipLabel.setVisible(false);
        requestLabel.setVisible(true);
        iptext.setVisible(false);
        startClient.setVisible(false);
        

imgLabel.setSize(new java.awt.Dimension(1300, 800));
        imgLabel.setBounds(0, 0, 1300, 700);
        //ImageIcon image = resizeImageIcon(new ImageIcon(pathName+"1.jpg"), 1245, 700);
        //imgLabel.setIcon(new ImageIcon("home.jpg"));
         jLabel1.setBounds(0, 0, 1245, 710);
         
        new Test3(iptext.getText().trim(), this);
        

    }//GEN-LAST:event_startClientActionPerformed

    private void getGifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getGifActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChose = new JFileChooser();
        fileChose.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);
        
        int result = fileChose.showOpenDialog(this);

        // if user clicked Cancel button on dialog, return
        if (result == JFileChooser.CANCEL_OPTION) {
            return;
        }
        
        File fileName = fileChose.getSelectedFile(); // get File

        // display error if invalid
        
        if ((fileName == null) || (fileName.getName().equals(""))) {
            JOptionPane.showMessageDialog(this, "Invalid Name",
                    "Invalid Name", JOptionPane.ERROR_MESSAGE);
        }
        
       pathName = fileName.toString();
        System.out.println("pathname : " + pathName);
       addSlash();
        System.out.println("pathname : " + pathName);
    }//GEN-LAST:event_getGifActionPerformed
    public void addSlash()
    {
        String temp= "";
        int prev=0;
        for(int i=0;i<pathName.length();i++)
        {
            if( pathName.charAt(i) =='\\')
            {
                temp = temp+ pathName.substring(prev, i)+ "\\";
                System.out.println(pathName.substring(prev, i));
                prev= i;
               // temp = temp+ pathName.substring(prev,i-prev+1)+ 
            }
        
        }
        temp= temp+ pathName.substring(prev, pathName.length())+"\\"+ "\\";
        //System.out.println(temp);
    pathName = temp;
    
    
    
    }
    private void endScreenShareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_endScreenShareActionPerformed
        // TODO add your handling code here:
        clientTerminate=true;
        
        
    }//GEN-LAST:event_endScreenShareActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClientFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClientFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClientFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClientFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClientFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton endScreenShare;
    private javax.swing.JButton getGif;
    public javax.swing.JLabel imgLabel;
    private javax.swing.JLabel ipLabel;
    private javax.swing.JTextField iptext;
    private javax.swing.JLabel jLabel1;
    public javax.swing.JPanel jPanel1;
    public javax.swing.JLabel requestLabel;
    private javax.swing.JButton startClient;
    // End of variables declaration//GEN-END:variables
}
