/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package multiclient;

import java.awt.AWTException;
import java.io.IOException;
import java.net.ServerSocket;
import java.net.Socket;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author Ehsan
 */
public class Home extends javax.swing.JFrame {

    public boolean serverOn[],messengerMode[],screenFlag[];
    public boolean freePos[];
    Socket socket;
    public int clientNumber;
    public boolean screenShareOn[];

    /**
     * Creates new form Home
     */
    public Home() {

        initComponents();
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public void init() {
        
        serverOn = new boolean[5];
        messengerMode = new boolean[5];
        screenFlag = new boolean[5];
        screenShareOn = new boolean[4];
        freePos= new boolean[5];
        freePos[0]= false;
        freePos[1]= false;
        
        
        
        serverOn[0]=false;
        serverOn[1]=false;
        messengerMode[0]=false;
        messengerMode[1]=false;
        screenFlag[0]=true;
        screenFlag[1]=true;
        
        
        
        clientNumber = 0;
        screenShareOn[0]=false;
        screenShareOn[1]=false;
        
        serverRunningLabel.setVisible(false);
        clientlabel1.setVisible(false);
        clientLabel2.setVisible(false);
        screenShare1.setVisible(false);
        Message1.setVisible(false);
        screenShare2.setVisible(false);
        Message2.setVisible(false); 
        

    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        startServer = new javax.swing.JButton();
        startClient = new javax.swing.JButton();
        serverRunningLabel = new javax.swing.JLabel();
        clientlabel1 = new javax.swing.JLabel();
        screenShare1 = new javax.swing.JButton();
        Message1 = new javax.swing.JButton();
        clientLabel2 = new javax.swing.JLabel();
        screenShare2 = new javax.swing.JButton();
        Message2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setPreferredSize(new java.awt.Dimension(200, 200));
        jPanel1.setLayout(null);

        startServer.setBackground(new java.awt.Color(27, 113, 241));
        startServer.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        startServer.setForeground(new java.awt.Color(240, 240, 240));
        startServer.setText("Start Server");
        startServer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startServerActionPerformed(evt);
            }
        });
        jPanel1.add(startServer);
        startServer.setBounds(180, 170, 160, 40);

        startClient.setBackground(new java.awt.Color(27, 113, 241));
        startClient.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        startClient.setForeground(new java.awt.Color(240, 240, 240));
        startClient.setText("Start Client");
        startClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startClientActionPerformed(evt);
            }
        });
        jPanel1.add(startClient);
        startClient.setBounds(180, 290, 160, 40);

        serverRunningLabel.setFont(new java.awt.Font("Lucida Calligraphy", 1, 18)); // NOI18N
        serverRunningLabel.setForeground(new java.awt.Color(255, 255, 255));
        serverRunningLabel.setText("Server is running.....");
        jPanel1.add(serverRunningLabel);
        serverRunningLabel.setBounds(190, 20, 250, 30);

        clientlabel1.setFont(new java.awt.Font("Lucida Calligraphy", 1, 12)); // NOI18N
        clientlabel1.setForeground(new java.awt.Color(255, 255, 255));
        clientlabel1.setText("Client 1 is connected");
        jPanel1.add(clientlabel1);
        clientlabel1.setBounds(10, 60, 200, 20);

        screenShare1.setBackground(new java.awt.Color(27, 113, 241));
        screenShare1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        screenShare1.setForeground(new java.awt.Color(255, 255, 255));
        screenShare1.setText("Start Screen");
        screenShare1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                screenShare1ActionPerformed(evt);
            }
        });
        jPanel1.add(screenShare1);
        screenShare1.setBounds(230, 60, 110, 30);

        Message1.setBackground(new java.awt.Color(27, 113, 241));
        Message1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Message1.setForeground(new java.awt.Color(240, 240, 240));
        Message1.setText("Message");
        Message1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Message1ActionPerformed(evt);
            }
        });
        jPanel1.add(Message1);
        Message1.setBounds(380, 60, 90, 30);

        clientLabel2.setFont(new java.awt.Font("Lucida Calligraphy", 1, 12)); // NOI18N
        clientLabel2.setForeground(new java.awt.Color(255, 255, 255));
        clientLabel2.setText("Client 2 is connected");
        jPanel1.add(clientLabel2);
        clientLabel2.setBounds(10, 100, 180, 20);

        screenShare2.setBackground(new java.awt.Color(27, 113, 241));
        screenShare2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        screenShare2.setForeground(new java.awt.Color(240, 240, 240));
        screenShare2.setText("Start Screen");
        screenShare2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                screenShare2ActionPerformed(evt);
            }
        });
        jPanel1.add(screenShare2);
        screenShare2.setBounds(230, 100, 110, 30);

        Message2.setBackground(new java.awt.Color(27, 113, 241));
        Message2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Message2.setForeground(new java.awt.Color(240, 240, 240));
        Message2.setText("Message");
        Message2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Message2ActionPerformed(evt);
            }
        });
        jPanel1.add(Message2);
        Message2.setBounds(380, 100, 90, 30);

        jLabel1.setIcon(new ImageIcon("home.jpg"));
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 620, 600);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 606, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void startServerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startServerActionPerformed
        setMinimumSize(new java.awt.Dimension(600, 600));
        setPreferredSize(new java.awt.Dimension(1200, 700));
        startClient.setVisible(false);
        startServer.setVisible(false);
        serverRunningLabel.setVisible(true);
        serverOn[0]=true;
        new Server(this).start();


    }//GEN-LAST:event_startServerActionPerformed

    private void startClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startClientActionPerformed
        // TODO add your handling code here:
        setVisible(false);
     java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClientFrame().setVisible(true);
            }
        });
    }//GEN-LAST:event_startClientActionPerformed

    private void screenShare1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_screenShare1ActionPerformed
        // TODO add your handling code here:
        System.out.println("Butt1");
        //System.out.println(screenShareOn);
        if(screenFlag[0])
        {
            screenShareOn[0]=true;
            screenShare1.setText("Stop Screen");  
            screenFlag[0] = false;
        }
        else
        {
            screenShare1.setVisible(false);
            Message1.setVisible(false); 
            clientlabel1.setVisible(false); 
            screenShareOn[0]= false;
            freePos[0]=false;
            System.out.println("dhuklm else");
            
        }
        
        
        
    }//GEN-LAST:event_screenShare1ActionPerformed

    private void Message1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Message1ActionPerformed
        // TODO add your handling code here:
        messengerMode[0] = true;
        screenShareOn[0]=true;
        
        
        
    }//GEN-LAST:event_Message1ActionPerformed

    private void screenShare2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_screenShare2ActionPerformed
        // TODO add your handling code here:
        System.out.println("Butt2"+screenFlag[1]);
        if(screenFlag[1])
        {
            SwingUtilities.invokeLater(
                new Runnable() {
                    public void run() {
                        screenShareOn[1]=true;
            System.out.println("vua");
            screenShare2.setText("Stop Screen");  
            screenFlag[1] = false;
                    }
                }
        );
            
        }
        else
        {
            screenShare2.setVisible(false);
            Message2.setVisible(false); 
            clientLabel2.setVisible(false); 
            screenShareOn[1]= false;
            freePos[1]=false;
            
            System.out.println("dhuklm else");
            
        }
        
    }//GEN-LAST:event_screenShare2ActionPerformed

    private void Message2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Message2ActionPerformed
        // TODO add your handling code here:
         messengerMode[1] = true;
        screenShareOn[1]=true;
        System.out.println("client2 chapse");
    }//GEN-LAST:event_Message2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton Message1;
    public javax.swing.JButton Message2;
    public javax.swing.JLabel clientLabel2;
    public javax.swing.JLabel clientlabel1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    public javax.swing.JPanel jPanel1;
    public javax.swing.JButton screenShare1;
    public javax.swing.JButton screenShare2;
    private javax.swing.JLabel serverRunningLabel;
    private javax.swing.JButton startClient;
    private javax.swing.JButton startServer;
    // End of variables declaration//GEN-END:variables
}
